[package]
name = "mcrender"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.4"
async-channel = "2.1"
bytemuck = { version = "1.14", features = ["derive"] }
png = "0.17"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
wgpu = "0.18"
