[package]
name = "mcrender"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.4"
async-channel = "2.1"
png = "0.17"
pollster = "0.3"
wgpu = "0.18"
